### ISSUE TITLE
Increase side panel opacity (decrease transparency)

### ISSUE THREAD

**Issue by Symbian9** [korzhyk/alert-map#1]
Панель занадто прозора - текст читати важко, бо змішується з підложкою

![Screenshot from 2022-04-22 14-44-40](https://user-images.githubusercontent.com/13188580/164708567-2a6df779-9b42-4509-9468-f8ad7f7d9327.png)

**Comment by korzhyk** [comment]
так, тут мав би використовуватись `backdrop-filter: blur()`, виглядає дійсно всрато.
